### PR TITLE
Support registering custom validation rules through validation mixin

### PR DESCRIPTION
**Pull request by vladimyr**
There are two benefits of this _new_ approach:
1. It de-clutters component code by moving rules outside of component definition
2. It ensures that rules are injected at creation instead of rendering time

### CODE REVIEW

**Comment by vladimyr** [comment]
@underscope Can we merge this into develop? :bowtie:

**Comment by vladimyr** [comment]
Additional goodies:
- Implemented generic `uniqueProp` validator factory

**Comment by zcuric** [comment]
@vladimyr what's the status of this?

**Comment by underscope** [comment]
No longer applicable

**Pull request closed without merging**
