### PR TITLE
Use EE eslint-config

### PR DESCRIPTION
**Pull request by ttokic**

### CODE REVIEW

**Comment by zcuric** [comment]
Very nice!

**Comment by zcuric** [comment]
Please run `npm run lint:js -- --fix`.

**Review by zcuric — APPROVED** [review]

**Review by zcuric — CHANGES_REQUESTED** [review]
Please run `npm run lint:js -- --fix` and fix other issues that need manual fix.

**Review by zcuric — APPROVED** [review]
👍

**Review by vladimyr — APPROVED** [review]

**Review by kronicker — APPROVED** [review]

**Pull request merged**
