### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by zcuric**
### This PR

- [x] Update dependencies to latest versions
- [x] Updates engines - `node` to latest LTS and `npm` to lates version
- [x] Resolves issues caused by new version of VeeValidate (thanks to @kronicker)

### CODE REVIEW

**Review by vladimyr — APPROVED** [review]

**Comment by vladimyr** [comment]
@kjuej Please do quick regression testing before this one gets merged 🙏

**Comment by zcuric** [comment]
@vladimyr what's the status?

**Comment by vladimyr** [comment]
> @vladimyr what's the status?

Waiting for @kjuej to verify that everything works 🙏

**Comment by kjuej** [comment]
@zcuric @vladimyr Seems there's an issue when creating a program.
screen shot 2019-03-06 at 13 19 29

**Comment by zcuric** [comment]
@kjuej I'll look to it's related with updates.

**Comment by zcuric** [comment]
@kjuej Issue fixed and deps update again. Can you please do a regression testing again? Thank you!

**Pull request merged**
